public enum Type {
    COMMENT,
    WHITESPACE,
    IDENTIFIER,
    OPERATOR,
    PARENTHESES,
    DELIMITER_CHARACTERS,
    INT_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    BOOLEAN_LITERAL,
    STRING_LITERAL,
    RESERVED_WORDS,
    ERROR
}
