public enum Type {
    COMMENT,
    WHITESPACE,
    IDENTIFIER,
    OPERATOR,
    PARENTHESES,
    DELIMITER_CHARACTER,
    INT_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    DEFINED_METHOD,
    BOOLEAN_LITERAL,
    STRING_LITERAL,
    RESERVED_WORDS,
    ERROR
}
